server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client: 
    #表示是否将自己注册到Eureka Server上，默认为true
    registerWithEureka: false
    #表示是否从Eureka Server上获取注册信息，默认为true
    fetchRegistry: false
    #Eureka Server的访问地址，服务注册和client获取服务注册
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/