eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring: 
  application:
    name: demo-config
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/chen1818/spring-cloud-config/
          username: XXXXXX
          password: XXXXXX

  